name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11

      - uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

      - uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./rotary-signin-service

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./rotary-signin-service

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true