name: docker
on:
  push:
    tags: [ "*.*.*" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - run: chmod +x gradlew
        working-directory: ./rotary-signin-service

      - run: ./gradlew -Penv=uat docker
        working-directory: ./rotary-signin-service

      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        working-directory: ./rotary-signin-service

      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ROTARY_SYS_SECRET }}

      - id: repo
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ env.GITHUB_REPOSITORY }}

      - run: echo ${{ steps.repo.outputs.lowercase }}

      - uses: docker/build-push-action@v2
        with:
          context: "rotary-signin-service/build/application/docker"
          tags: "${{ env.REGISTRY }}/${{ steps.repo.outputs.lowercase }}/rotary-signin-service:${{ env.TAG }}, ${{ env.REGISTRY }}/${{ github.repository }}/rotary-signin-service:latest"
          push: true