name: docker
on:
  push:
    tags: [ "*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - run: ./gradlew -Penv=uat -p ext docker
        working-directory: ./rotary-signin-service

      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        working-directory: ./rotary-signin-service

      - uses: docker/login-action@v1
        with:
          username: neobradley
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v2
        working-directory: ./rotary-signin-service
        with:
          context: "build/application/docker"
          tags: "silmoontravis/rotary-signin-service:${{ env.TAG }}, silmoontravis/rotary-signin-service:latest"
          push: true