name: docker
on:
  push:
    tags: [ "*.*.*" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - run: chmod +x gradlew
        working-directory: ./rotary-signin-service

      - run: ./gradlew -Penv=uat docker
        working-directory: ./rotary-signin-service

      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        working-directory: ./rotary-signin-service

      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ROTARY_SYS_SECRET }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.pkg.github.com/${{ github.repository }}
          tags: |
            type=raw,enable=true,pattern={{version}},value=latest,latest=true

      - uses: docker/build-push-action@v2
        with:
          context: "rotary-signin-service/build/application/docker"
          tags: ${{ steps.meta.outputs.tags }}, ${{ steps.meta.outputs.tags }}
          push: true